[tox]
isolated_build = True
envlist = fmt, lint, mypy,
    py312-django{52,60,main}
    py313-django{52,60,main}

[testenv]
deps =
    pytest
    pytest-cov
    pytest-django
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    djangomain: https://github.com/django/django/archive/main.tar.gz

commands =
    pytest --ds=tests.settings --cov=elasticsearch_django --verbose tests

[testenv:fmt]
description = 'Source file formatting'
deps =
    black

commands =
    black elasticsearch_django

[testenv:lint]
description = 'Source file linting'
deps =
    ruff

commands =
    ruff check elasticsearch_django

[testenv:mypy]
deps =
    mypy

commands =
    mypy elasticsearch_django
