[tox]
isolated_build = True
envlist = fmt, lint, mypy,
    py310-django{42,50,52,main}
    py311-django{42,50,52,main}
    py312-django{42,50,52,main}

[testenv]
deps =
    pytest
    pytest-cov
    pytest-django
    django42: Django>=4.2,<4.3
    django50: Django>=5.0,<5.1
    django52: Django>=5.2,<5.3
    djangomain: https://github.com/django/django/archive/main.tar.gz

commands =
    pytest --ds=tests.settings --cov=elasticsearch_django --verbose tests

[testenv:fmt]
description = 'Source file formatting'
deps =
    black

commands =
    black elasticsearch_django

[testenv:lint]
description = 'Source file linting'
deps =
    ruff

commands =
    ruff check elasticsearch_django

[testenv:mypy]
deps =
    mypy

commands =
    mypy elasticsearch_django
