# Generated by Django 2.1.3 on 2018-12-03 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elasticsearch_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sample', models.TextField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Recommended Retail Price')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(elasticsearch_django.models.SearchDocumentMixin, models.Model),
        ),
    ]
