# Generated by Django 3.0.8 on 2020-07-29 08:35

from django.db import migrations, models

import elasticsearch_django.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("simple_field_1", models.IntegerField()),
                ("simple_field_2", models.CharField(max_length=100)),
                ("complex_field", models.FileField(upload_to="")),
            ],
            bases=(elasticsearch_django.models.SearchDocumentMixin, models.Model),
        ),
    ]
