# Generated by Django 4.1.1 on 2022-09-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elasticsearch_django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_examplemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModelWithCustomPrimaryKey',
            fields=[
                ('simple_field_1', models.IntegerField(primary_key=True, serialize=False)),
                ('simple_field_2', models.CharField(max_length=100)),
                ('complex_field', models.FileField(upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(elasticsearch_django.models.SearchDocumentMixin, models.Model),
        ),
    ]
