# Generated by Django 4.1.1 on 2022-10-01 14:00

import uuid

import django.db.models.deletion
from django.db import migrations, models

import elasticsearch_django.models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0003_examplemodelwithcustomprimarykey"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_1", models.UUIDField(default=uuid.uuid4)),
                ("field_2", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ModelB",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.modela"
                    ),
                ),
            ],
            bases=(elasticsearch_django.models.SearchDocumentMixin, models.Model),
        ),
    ]
